-- MySQL Script generated by MySQL Workbench
-- Thu Oct 19 09:03:09 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema naming
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `naming` ;

-- -----------------------------------------------------
-- Schema naming
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `naming` DEFAULT CHARACTER SET utf8 ;
USE `naming` ;

-- -----------------------------------------------------
-- Table `naming`.`system`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `naming`.`system` ;

CREATE TABLE IF NOT EXISTS `naming`.`system` (
  `system_id` INT NOT NULL AUTO_INCREMENT,
  `system_name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`system_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `naming`.`subsystem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `naming`.`subsystem` ;

CREATE TABLE IF NOT EXISTS `naming`.`subsystem` (
  `subsystem_id` INT NOT NULL AUTO_INCREMENT,
  `subsystem_name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`subsystem_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `naming`.`device_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `naming`.`device_type` ;

CREATE TABLE IF NOT EXISTS `naming`.`device_type` (
  `deviceType_id` INT NOT NULL AUTO_INCREMENT,
  `device_type` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`deviceType_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `naming`.`device`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `naming`.`device` ;

CREATE TABLE IF NOT EXISTS `naming`.`device` (
  `device_id` INT NOT NULL AUTO_INCREMENT,
  `qualifier` VARCHAR(45) NULL,
  `instance` VARCHAR(45) NULL,
  `system` INT NOT NULL,
  `subsystem` INT NULL,
  `device_type` INT NULL,
  PRIMARY KEY (`device_id`),
  INDEX `fk_system_idx` (`system` ASC),
  INDEX `fk_subsystem_idx` (`subsystem` ASC),
  INDEX `fk_deviceType_idx` (`device_type` ASC),
  CONSTRAINT `fk_system`
    FOREIGN KEY (`system`)
    REFERENCES `naming`.`system` (`system_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subsystem`
    FOREIGN KEY (`subsystem`)
    REFERENCES `naming`.`subsystem` (`subsystem_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_deviceType`
    FOREIGN KEY (`device_type`)
    REFERENCES `naming`.`device_type` (`deviceType_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `naming`.`signal_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `naming`.`signal_type` ;

CREATE TABLE IF NOT EXISTS `naming`.`signal_type` (
  `signalType_id` INT NOT NULL AUTO_INCREMENT,
  `signal_type` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`signalType_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `naming`.`signal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `naming`.`signal` ;

CREATE TABLE IF NOT EXISTS `naming`.`signal` (
  `signal_id` INT NOT NULL AUTO_INCREMENT,
  `device` INT NULL,
  `signalType` INT NULL,
  PRIMARY KEY (`signal_id`),
  INDEX `fk_device_idx` (`device` ASC),
  INDEX `fk_signalType_idx` (`signalType` ASC),
  CONSTRAINT `fk_device`
    FOREIGN KEY (`device`)
    REFERENCES `naming`.`device` (`device_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_signalType`
    FOREIGN KEY (`signalType`)
    REFERENCES `naming`.`signal_type` (`signalType_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
